function [ comparison, trialSpec ] = list_trialSpecs( analysisName )

switch analysisName
    case 'bootAvg'
        subsets = {...
            'choice_correct',...
            {'left' 'correct'},...
            {'right' 'correct'};... 

            'outcome',...
            {'correct'},...
            {'error'};...

            }; %Spec for each trial subset for comparison (conjunction of N fields from 'trials' structure.)

        comparison = subsets(:,1);
        trialSpec = subsets(:,2:3);

end