matfiles.cohort1 =... 
    {'C:\Data\Task Learning\results\mjs_taskLearning_NAc_DREADD2\mjs20_11.mat';...
    'C:\Data\Task Learning\results\mjs_taskLearning_NAc_DREADD2\mjs20_12.mat';...
    'C:\Data\Task Learning\results\mjs_taskLearning_NAc_DREADD2\mjs20_13.mat';...
    'C:\Data\Task Learning\results\mjs_taskLearning_NAc_DREADD2\mjs20_14.mat';...
    'C:\Data\Task Learning\results\mjs_taskLearning_NAc_DREADD2\mjs20_15.mat';...
    'C:\Data\Task Learning\results\mjs_taskLearning_NAc_DREADD2\mjs20_16.mat';...
    'C:\Data\Task Learning\results\mjs_taskLearning_NAc_DREADD2\mjs20_17.mat'};
matfiles.cohort2 =... 
    {'C:\Data\LMaze\results\mjs_taskLearningWalls\mjs20_09.mat';...
    'C:\Data\LMaze\results\mjs_taskLearningWalls\mjs20_09.mat';...
    'C:\Data\LMaze\results\mjs_taskLearningWalls\mjs20_09.mat';...
    'C:\Data\LMaze\results\mjs_taskLearningWalls\mjs20_09.mat';...
    'C:\Data\LMaze\results\mjs_taskLearningWalls\mjs20_09.mat'};

for i = 1:numel(matfiles.cohort1)
    cohort1(i) = load(matfiles.cohort1{i});
end
for i = 1:numel(matfiles.cohort2)
    cohort2(i) = load(matfiles.cohort2{i});
end