% root_dir = 'Y:\michael\i2c-test\';

tif_path = 'Y:\michael\i2c-test\i2c-test_00002_00001.tif';

[stack, tags, ImageDescription] =  loadtiffseq(...
        tif_path,[]); % load raw stack (.tif)
stackInfo.I2C = getI2CData(vertcat(ImageDescription));

% [dirs, paths] = iCorreFilePaths(root_dir, data_dirs{i}, params.source_dir);
% stackInfo = tiff2mat_parallel(paths.source, paths.mat,... 
%             struct(...
%             'chan_number',params.ref_channel,...
%             'crop_margins',params.crop_margins,...
%             'read_method',params.read_method,...
%             'extract_I2C',params.saveI2CData && strcmp(dirs.source,dirs.raw))); %Extract I2C data only if starting from raw TIFFs
%      